### ISSUE TITLE
mod_pagespeed option not in WHM

### ISSUE THREAD

**Issue by ghost** [apache/incubator-pagespeed-cpanel#2]
HI,

I did:
 git clone http://github.com/pagespeed/cpanel.git /var/cpanel/easy/apache/custom_opt_mods/mod_pagespeed

The files were correctly copy and I can see them. Now if I have no misunderstood, in 
WHM -> EasyApache (Apache Update)-> Exhaustive list
The option of mod_pagespeed should be present for me to select.

It is not there :(
I am running 
CENTOS 6.4 x86_64 
Apache 2.2.24 
Easy::Apache v3.18.13
with cPanel 11.36.1

Any tips?

**Comment by wiredhosting** [comment]
Can you update installation instruction For cPanel users that still use Easyapache 3?

THanks!

follow this steps.


Step1: COPY
/usr/local/cpanel/3rdparty/bin/git clone https://github.com/pagespeed/cpanel.git /var/cpanel/easy/apache/custom_opt_mods/Cpanel/


Step 2: Create a Speed.pm.tar.gz
cd /var/cpanel/easy/apache/custom_opt_mods/Cpanel/Easy
tar -zcvf Speed.pm.tar.gz pagespeed

Step 3: In cPanel WHM-> EasyApache - You will see the mod_pagepeed in the options to compile. Check and compile.
